# Generated by Django 3.2.18 on 2023-03-28 11:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_recipe'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Recipe',
        ),
        migrations.RenameField(
            model_name='comment',
            old_name='Post',
            new_name='post',
        ),
    ]
