# Generated by Django 3.2.18 on 2023-04-05 16:28

from django.db import migrations, models
import djrichtextfield.models


class Migration(migrations.Migration):
    dependencies = [
        ("recipe_maker", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="recipe",
            name="ingredients",
            field=djrichtextfield.models.RichTextField(default="", max_length=10000),
        ),
        migrations.AlterField(
            model_name="recipe",
            name="cuisine_types",
            field=models.CharField(
                choices=[
                    ("african", "African"),
                    ("american", "American"),
                    ("caribbean", "Caribbean"),
                    ("asian", "Asian"),
                    ("middle_eastern", "Middle Eastern"),
                    ("chinese", "Chinese"),
                    ("indian", "Indian"),
                    ("pakistani", "Pakistani"),
                    ("indonesian", "Indonesian"),
                    ("european", "European"),
                ],
                default="african",
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="recipe",
            name="meal_type",
            field=models.CharField(
                choices=[
                    ("breakfast", "Breakfast"),
                    ("lunch", "Lunch"),
                    ("dinner", "Dinner"),
                ],
                default="breakfast",
                max_length=50,
            ),
        ),
    ]
