# Generated by Django 3.2.18 on 2023-04-15 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe_maker', '0003_alter_recipe_cuisine_types'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='meal_type',
            field=models.CharField(choices=[('easy', 'Easy'), ('Medium', 'Medium'), ('hard', 'Hard')], default='breakfast', max_length=50),
        ),
    ]
