# Generated by Django 3.2.18 on 2023-04-19 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe_maker', '0004_alter_recipe_meal_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='meal_type',
            field=models.CharField(choices=[('easy', 'Easy'), ('Medium', 'Medium'), ('hard', 'Hard')], default='easy', max_length=50),
        ),
    ]
